plugins: [jekyll-paginate, jemoji]
permalink: pretty

title: Ask
url: https://mx-psi.github.io
baseurl: /ask
paginate: 20

author:
  name: 'Sparkles'
  twitter: mx_psi

avatar: public/avatar.jpg
banner: public/banner.jpg
