plugins: [jekyll-paginate, jemoji]
permalink: pretty

title: Ask
url: https://drxaverius.github.io
baseurl: /ask
paginate: 20

author:
  name: 'DrXaverius'
  twitter: drxaverius

avatar: public/avatar.jpg
banner: public/banner.jpg
